### ISSUE TITLE
[RFE] show most recent entries/stories

### ISSUE THREAD

**Issue by TomasTomecek** [redhat-exd-rebuilds/estuary#29]
I just opened the app. Since I have no idea about IDs of bugzillas or erratas, I can't really see anything.

Would it be possible to show last 3 entries, or something like that?

**Comment by hanzz** [comment]
+1, it would be great to also see last N Freshmaker events, I could then use it instead of "freshmaker-cli".

**Comment by mprahl** [comment]
@TomasTomecek and @hanzz: Do you want a drop-down under the input box with the last few entries that appears before you start typing or do you want a separate part of the search/landing page dedicated to showing recently update artifacts?

This isn't completely relevant but FACTORY-2363 will simplify the "search" by allowing you to provide more human readable values (e.g. advisory name instead of just IDs). That is coming soon.

**Comment by hanzz** [comment]
For my use-case (I check the latest Freshmaker builds at least every morning :) ), the landing page with last events would be better.

**Comment by TomasTomecek** [comment]
Both of them sounds good to me.

**Comment by mprahl** [comment]
This has been implemented for a while now, I just forgot to close the ticket.
